apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cardmarket-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Lekeleebusiness/interview.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cardmarket

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true