namespace: cardmarket

replicaCount: 1

image:
  repository: lekelee/simple-k8s-node-app
  tag: "8acf1e48d6b928275c52af8eeef82628680a0ca5"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  className: nginx
  host: cardmarket.local